server:
    port: 8778

debug: true

spring:
    cloud:
        zookeeper:
            connectString: 127.0.0.1:2181
            enabled: false
    sleuth:
        enabled: false

swagger:
    basePackage: com.ctgpaas.dcos.controller
    title: ctg-ctgpaas-dcos RESTful APIs
    description: ctg-ctgpaas-dcos RESTful API
    version: 1.0.0-SNAPSHOT
    openApi:
        group: OpenApi
        basePackage: com.ctgpaas.dcos.controller
        title: actg-ctgpaas-dcos Open APIs
        description: ctg-ctgpaas-dcos Open API
        version: 1.0.0-SNAPSHOT
